/**
 * Auth integration tests — signup → OTP → verify → /me → refresh.
 *
 * Connects to a `trustpe-test` database on the same Atlas cluster as the dev
 * backend. The DB is dropped before and after the run so tests are isolated
 * from dev data.
 *
 * Requires MONGO_URI to be set (e.g., via backend/.env or shell env). If unset,
 * the whole suite is skipped with a clear message instead of failing.
 *
 * NOTE: Atlas connection-string format normally ends with `/<dbname>?<opts>`.
 * This file rewrites the path segment to `trustpe-test` regardless of what's
 * there, so dev data (in `trustpe-dev` or whatever name you used) is untouched.
 */
import 'dotenv/config';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import type { Express } from 'express';
import mongoose from 'mongoose';

const TEST_DB_NAME = 'trustpe-test';

function buildTestUri(rawUri: string): string {
  // Replace the database segment in either `mongodb://host/<db>?...` or
  // `mongodb+srv://host/<db>?...`. Tolerates missing/empty db name.
  const url = new URL(rawUri);
  url.pathname = `/${TEST_DB_NAME}`;
  return url.toString();
}

const baseUri = process.env.MONGO_URI;

// If no Mongo URI configured, skip the whole suite with a clear note rather
// than failing in CI / when someone clones fresh.
const describeWithMongo = baseUri ? describe : describe.skip;

let app: Express;

beforeAll(async () => {
  process.env.JWT_ACCESS_SECRET =
    process.env.JWT_ACCESS_SECRET ?? 'test-access-secret-must-be-at-least-32-chars-long';
  process.env.JWT_REFRESH_SECRET =
    process.env.JWT_REFRESH_SECRET ?? 'test-refresh-secret-must-be-at-least-32-chars-long';

  if (!baseUri) {
    // eslint-disable-next-line no-console
    console.warn('[auth.test] Skipping — set MONGO_URI in backend/.env to enable integration tests.');
    return;
  }

  const testUri = buildTestUri(baseUri);
  process.env.MONGO_URI = testUri;

  await mongoose.connect(testUri);
  // Wipe the test DB so previous runs don't bleed in.
  await mongoose.connection.dropDatabase();

  const { createApp } = await import('../../src/app.js');
  app = createApp();
}, 60_000);

afterAll(async () => {
  try {
    if (mongoose.connection.readyState !== 0) {
      await mongoose.connection.dropDatabase();
      await mongoose.disconnect();
    }
  } catch {
    /* ignore */
  }
}, 30_000);

beforeEach(async () => {
  if (!baseUri) return;
  const { collections } = mongoose.connection;
  await Promise.all(Object.values(collections).map((c) => c.deleteMany({})));
  const { otpStoreService } = await import('../../src/services/otp-store.service.js');
  otpStoreService._reset();
});

describeWithMongo('Auth — signup + OTP + verify + refresh + /me', () => {
  // Capture OTPs as they're generated by spying on the email service.
  let capturedOtp: string | null = null;
  beforeAll(async () => {
    if (!baseUri) return;
    const mod = await import('../../src/services/email.service.js');
    const original = mod.emailService.sendOtp.bind(mod.emailService);
    mod.emailService.sendOtp = async (to, otp, purpose) => {
      capturedOtp = otp;
      return original(to, otp, purpose);
    };
  });
  beforeEach(() => {
    capturedOtp = null;
  });

  it('signup creates a user and dispatches an OTP', async () => {
    const res = await request(app).post('/v1/auth/signup').send({
      phone: '9876543210',
      email: '[email protected]',
      name: 'Alice Test',
    });

    expect(res.status).toBe(202);
    expect(res.body.ok).toBe(true);
    expect(res.body.data.otpSentTo).toBe('[email protected]');
    expect(capturedOtp).toMatch(/^\d{6}$/);
  });

  it('verify-otp issues tokens and moves user to onboarding', async () => {
    await request(app)
      .post('/v1/auth/signup')
      .send({ phone: '9876543210', email: '[email protected]', name: 'Alice' });
    const otp = capturedOtp!;

    const verify = await request(app)
      .post('/v1/auth/verify-otp')
      .send({ email: '[email protected]', otp });

    expect(verify.status).toBe(200);
    expect(verify.body.data.accessToken).toBeTypeOf('string');
    expect(verify.body.data.refreshToken).toMatch(/^[a-f0-9]{64}$/);
    expect(verify.body.data.user.status).toBe('onboarding');
    expect(verify.body.data.user.email).toBe('[email protected]');
  });

  it('verify-otp rejects an incorrect OTP', async () => {
    await request(app)
      .post('/v1/auth/signup')
      .send({ phone: '9876543210', email: '[email protected]', name: 'Alice' });

    const verify = await request(app)
      .post('/v1/auth/verify-otp')
      .send({ email: '[email protected]', otp: '000000' });

    expect(verify.status).toBe(400);
    expect(verify.body.error.code).toBe('otp_incorrect');
  });

  it('GET /v1/me returns the authenticated user', async () => {
    await request(app)
      .post('/v1/auth/signup')
      .send({ phone: '9876543210', email: '[email protected]', name: 'Alice' });
    const verify = await request(app)
      .post('/v1/auth/verify-otp')
      .send({ email: '[email protected]', otp: capturedOtp! });

    const me = await request(app)
      .get('/v1/me')
      .set('Authorization', `Bearer ${verify.body.data.accessToken}`);

    expect(me.status).toBe(200);
    expect(me.body.data.email).toBe('[email protected]');
    expect(me.body.data.trustScore).toBe(300);
    expect(me.body.data.trustBand).toBe('building');
  });

  it('refresh rotates the token and invalidates the old one', async () => {
    await request(app)
      .post('/v1/auth/signup')
      .send({ phone: '9876543210', email: '[email protected]', name: 'Alice' });
    const verify = await request(app)
      .post('/v1/auth/verify-otp')
      .send({ email: '[email protected]', otp: capturedOtp! });
    const firstRefresh = verify.body.data.refreshToken;

    const refresh1 = await request(app)
      .post('/v1/auth/refresh')
      .send({ refreshToken: firstRefresh });

    expect(refresh1.status).toBe(200);
    expect(refresh1.body.data.refreshToken).not.toBe(firstRefresh);

    // Old token should now be rejected and the chain killed.
    const replay = await request(app)
      .post('/v1/auth/refresh')
      .send({ refreshToken: firstRefresh });
    expect(replay.status).toBe(401);
    expect(replay.body.error.code).toBe('refresh_chain_killed');
  });
});
